
import React from 'react';
import { Nuance } from '../types';

interface DocumentCardProps {
    nuance: Nuance;
}

const DocumentSection: React.FC<{ title: string; content: string }> = ({ title, content }) => {
    // Basic markdown to HTML conversion for lists
    const formattedContent = content.split('\n').map((line, index) => {
        if (line.match(/^(\d+\.|-|\*)\s/)) {
            return <li key={index}>{line.replace(/^(\d+\.|-|\*)\s/, '')}</li>;
        }
        return <p key={index}>{line}</p>;
    });

    const isList = content.match(/^(\d+\.|-|\*)\s/m);

    return (
        <section className="mb-6">
            <h3 className="text-xl font-semibold text-gray-800 border-b-2 border-gray-300 pb-2 mb-3">{title}</h3>
            <div className={`prose prose-base max-w-none text-gray-700 leading-relaxed ${isList ? 'pl-5' : ''}`}>
                {isList ? <ul>{formattedContent}</ul> : formattedContent}
            </div>
        </section>
    );
};


const DocumentCard: React.FC<DocumentCardProps> = ({ nuance }) => {
    return (
        <div id="document-card" className="bg-white text-gray-900 p-8 sm:p-12 rounded-lg shadow-2xl">
            <header className="mb-8 text-center border-b border-gray-200 pb-6">
                <p className="text-sm font-semibold tracking-widest text-fuchsia-600 uppercase">UI/UX STRATEGY DOCUMENT</p>
                <h2 className="text-4xl font-bold text-gray-900 mt-2">{nuance.title}</h2>
                <p className="mt-3 text-base text-gray-600 max-w-2xl mx-auto">{nuance.detail}</p>
            </header>

            <main>
                <DocumentSection 
                    title="Key Objectives"
                    content={nuance.workshopContent?.keyObjectives || "No objectives defined."}
                />
                <DocumentSection 
                    title="Action Steps"
                    content={nuance.workshopContent?.actionSteps || "No action steps defined."}
                />
                <DocumentSection 
                    title="Success Metrics"
                    content={nuance.workshopContent?.successMetrics || "No success metrics defined."}
                />
            </main>
            
            <footer className="mt-8 pt-4 border-t border-gray-200 text-center">
                <p className="text-xs text-gray-500">
                    Generated by KARA | AI Family Nuances Initiative &copy; {new Date().getFullYear()}
                </p>
            </footer>
        </div>
    );
};

export default DocumentCard;
